/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RessourcenRouteImport } from './routes/ressourcen'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiIntegrationsDiscordCallbackRouteImport } from './routes/api/integrations/discord/callback'
import { Route as ApiIntegrationsDiscordConnectRouteImport } from './routes/api/integrations/discord/connect'
import { Route as ApiIntegrationsDiscordInteractionsRouteImport } from './routes/api/integrations/discord/interactions'
import { Route as ApiIntegrationsGithubCallbackRouteImport } from './routes/api/integrations/github/callback'
import { Route as ApiIntegrationsGithubConnectRouteImport } from './routes/api/integrations/github/connect'
import { Route as ApiInternalDiscordRolesSyncRouteImport } from './routes/api/internal/discord-roles/sync'
import { Route as ApiInternalGithubOrgSyncRouteImport } from './routes/api/internal/github-org/sync'
import { Route as ApiInternalGithubTeamsSyncRouteImport } from './routes/api/internal/github-teams/sync'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RessourcenRoute = RessourcenRouteImport.update({
  id: '/ressourcen',
  path: '/ressourcen',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntegrationsDiscordCallbackRoute =
  ApiIntegrationsDiscordCallbackRouteImport.update({
    id: '/api/integrations/discord/callback',
    path: '/api/integrations/discord/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsDiscordConnectRoute =
  ApiIntegrationsDiscordConnectRouteImport.update({
    id: '/api/integrations/discord/connect',
    path: '/api/integrations/discord/connect',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsDiscordInteractionsRoute =
  ApiIntegrationsDiscordInteractionsRouteImport.update({
    id: '/api/integrations/discord/interactions',
    path: '/api/integrations/discord/interactions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsGithubCallbackRoute =
  ApiIntegrationsGithubCallbackRouteImport.update({
    id: '/api/integrations/github/callback',
    path: '/api/integrations/github/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsGithubConnectRoute =
  ApiIntegrationsGithubConnectRouteImport.update({
    id: '/api/integrations/github/connect',
    path: '/api/integrations/github/connect',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalDiscordRolesSyncRoute =
  ApiInternalDiscordRolesSyncRouteImport.update({
    id: '/api/internal/discord-roles/sync',
    path: '/api/internal/discord-roles/sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalGithubOrgSyncRoute =
  ApiInternalGithubOrgSyncRouteImport.update({
    id: '/api/internal/github-org/sync',
    path: '/api/internal/github-org/sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalGithubTeamsSyncRoute =
  ApiInternalGithubTeamsSyncRouteImport.update({
    id: '/api/internal/github-teams/sync',
    path: '/api/internal/github-teams/sync',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/dashboard': typeof DashboardRoute
  '/datenschutz': typeof DatenschutzRoute
  '/faq': typeof FaqRoute
  '/impressum': typeof ImpressumRoute
  '/login': typeof LoginRoute
  '/ressourcen': typeof RessourcenRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/integrations/discord/callback': typeof ApiIntegrationsDiscordCallbackRoute
  '/api/integrations/discord/connect': typeof ApiIntegrationsDiscordConnectRoute
  '/api/integrations/discord/interactions': typeof ApiIntegrationsDiscordInteractionsRoute
  '/api/integrations/github/callback': typeof ApiIntegrationsGithubCallbackRoute
  '/api/integrations/github/connect': typeof ApiIntegrationsGithubConnectRoute
  '/api/internal/discord-roles/sync': typeof ApiInternalDiscordRolesSyncRoute
  '/api/internal/github-org/sync': typeof ApiInternalGithubOrgSyncRoute
  '/api/internal/github-teams/sync': typeof ApiInternalGithubTeamsSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/dashboard': typeof DashboardRoute
  '/datenschutz': typeof DatenschutzRoute
  '/faq': typeof FaqRoute
  '/impressum': typeof ImpressumRoute
  '/login': typeof LoginRoute
  '/ressourcen': typeof RessourcenRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/integrations/discord/callback': typeof ApiIntegrationsDiscordCallbackRoute
  '/api/integrations/discord/connect': typeof ApiIntegrationsDiscordConnectRoute
  '/api/integrations/discord/interactions': typeof ApiIntegrationsDiscordInteractionsRoute
  '/api/integrations/github/callback': typeof ApiIntegrationsGithubCallbackRoute
  '/api/integrations/github/connect': typeof ApiIntegrationsGithubConnectRoute
  '/api/internal/discord-roles/sync': typeof ApiInternalDiscordRolesSyncRoute
  '/api/internal/github-org/sync': typeof ApiInternalGithubOrgSyncRoute
  '/api/internal/github-teams/sync': typeof ApiInternalGithubTeamsSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/dashboard': typeof DashboardRoute
  '/datenschutz': typeof DatenschutzRoute
  '/faq': typeof FaqRoute
  '/impressum': typeof ImpressumRoute
  '/login': typeof LoginRoute
  '/ressourcen': typeof RessourcenRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/integrations/discord/callback': typeof ApiIntegrationsDiscordCallbackRoute
  '/api/integrations/discord/connect': typeof ApiIntegrationsDiscordConnectRoute
  '/api/integrations/discord/interactions': typeof ApiIntegrationsDiscordInteractionsRoute
  '/api/integrations/github/callback': typeof ApiIntegrationsGithubCallbackRoute
  '/api/integrations/github/connect': typeof ApiIntegrationsGithubConnectRoute
  '/api/internal/discord-roles/sync': typeof ApiInternalDiscordRolesSyncRoute
  '/api/internal/github-org/sync': typeof ApiInternalGithubOrgSyncRoute
  '/api/internal/github-teams/sync': typeof ApiInternalGithubTeamsSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connect'
    | '/dashboard'
    | '/datenschutz'
    | '/faq'
    | '/impressum'
    | '/login'
    | '/ressourcen'
    | '/api/auth/callback'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/integrations/discord/callback'
    | '/api/integrations/discord/connect'
    | '/api/integrations/discord/interactions'
    | '/api/integrations/github/callback'
    | '/api/integrations/github/connect'
    | '/api/internal/discord-roles/sync'
    | '/api/internal/github-org/sync'
    | '/api/internal/github-teams/sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connect'
    | '/dashboard'
    | '/datenschutz'
    | '/faq'
    | '/impressum'
    | '/login'
    | '/ressourcen'
    | '/api/auth/callback'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/integrations/discord/callback'
    | '/api/integrations/discord/connect'
    | '/api/integrations/discord/interactions'
    | '/api/integrations/github/callback'
    | '/api/integrations/github/connect'
    | '/api/internal/discord-roles/sync'
    | '/api/internal/github-org/sync'
    | '/api/internal/github-teams/sync'
  id:
    | '__root__'
    | '/'
    | '/connect'
    | '/dashboard'
    | '/datenschutz'
    | '/faq'
    | '/impressum'
    | '/login'
    | '/ressourcen'
    | '/api/auth/callback'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/integrations/discord/callback'
    | '/api/integrations/discord/connect'
    | '/api/integrations/discord/interactions'
    | '/api/integrations/github/callback'
    | '/api/integrations/github/connect'
    | '/api/internal/discord-roles/sync'
    | '/api/internal/github-org/sync'
    | '/api/internal/github-teams/sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectRoute: typeof ConnectRoute
  DashboardRoute: typeof DashboardRoute
  DatenschutzRoute: typeof DatenschutzRoute
  FaqRoute: typeof FaqRoute
  ImpressumRoute: typeof ImpressumRoute
  LoginRoute: typeof LoginRoute
  RessourcenRoute: typeof RessourcenRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiIntegrationsDiscordCallbackRoute: typeof ApiIntegrationsDiscordCallbackRoute
  ApiIntegrationsDiscordConnectRoute: typeof ApiIntegrationsDiscordConnectRoute
  ApiIntegrationsDiscordInteractionsRoute: typeof ApiIntegrationsDiscordInteractionsRoute
  ApiIntegrationsGithubCallbackRoute: typeof ApiIntegrationsGithubCallbackRoute
  ApiIntegrationsGithubConnectRoute: typeof ApiIntegrationsGithubConnectRoute
  ApiInternalDiscordRolesSyncRoute: typeof ApiInternalDiscordRolesSyncRoute
  ApiInternalGithubOrgSyncRoute: typeof ApiInternalGithubOrgSyncRoute
  ApiInternalGithubTeamsSyncRoute: typeof ApiInternalGithubTeamsSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ressourcen': {
      id: '/ressourcen'
      path: '/ressourcen'
      fullPath: '/ressourcen'
      preLoaderRoute: typeof RessourcenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/discord/callback': {
      id: '/api/integrations/discord/callback'
      path: '/api/integrations/discord/callback'
      fullPath: '/api/integrations/discord/callback'
      preLoaderRoute: typeof ApiIntegrationsDiscordCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/discord/connect': {
      id: '/api/integrations/discord/connect'
      path: '/api/integrations/discord/connect'
      fullPath: '/api/integrations/discord/connect'
      preLoaderRoute: typeof ApiIntegrationsDiscordConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/discord/interactions': {
      id: '/api/integrations/discord/interactions'
      path: '/api/integrations/discord/interactions'
      fullPath: '/api/integrations/discord/interactions'
      preLoaderRoute: typeof ApiIntegrationsDiscordInteractionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/github/callback': {
      id: '/api/integrations/github/callback'
      path: '/api/integrations/github/callback'
      fullPath: '/api/integrations/github/callback'
      preLoaderRoute: typeof ApiIntegrationsGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/github/connect': {
      id: '/api/integrations/github/connect'
      path: '/api/integrations/github/connect'
      fullPath: '/api/integrations/github/connect'
      preLoaderRoute: typeof ApiIntegrationsGithubConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/discord-roles/sync': {
      id: '/api/internal/discord-roles/sync'
      path: '/api/internal/discord-roles/sync'
      fullPath: '/api/internal/discord-roles/sync'
      preLoaderRoute: typeof ApiInternalDiscordRolesSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/github-org/sync': {
      id: '/api/internal/github-org/sync'
      path: '/api/internal/github-org/sync'
      fullPath: '/api/internal/github-org/sync'
      preLoaderRoute: typeof ApiInternalGithubOrgSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/github-teams/sync': {
      id: '/api/internal/github-teams/sync'
      path: '/api/internal/github-teams/sync'
      fullPath: '/api/internal/github-teams/sync'
      preLoaderRoute: typeof ApiInternalGithubTeamsSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectRoute: ConnectRoute,
  DashboardRoute: DashboardRoute,
  DatenschutzRoute: DatenschutzRoute,
  FaqRoute: FaqRoute,
  ImpressumRoute: ImpressumRoute,
  LoginRoute: LoginRoute,
  RessourcenRoute: RessourcenRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiIntegrationsDiscordCallbackRoute: ApiIntegrationsDiscordCallbackRoute,
  ApiIntegrationsDiscordConnectRoute: ApiIntegrationsDiscordConnectRoute,
  ApiIntegrationsDiscordInteractionsRoute:
    ApiIntegrationsDiscordInteractionsRoute,
  ApiIntegrationsGithubCallbackRoute: ApiIntegrationsGithubCallbackRoute,
  ApiIntegrationsGithubConnectRoute: ApiIntegrationsGithubConnectRoute,
  ApiInternalDiscordRolesSyncRoute: ApiInternalDiscordRolesSyncRoute,
  ApiInternalGithubOrgSyncRoute: ApiInternalGithubOrgSyncRoute,
  ApiInternalGithubTeamsSyncRoute: ApiInternalGithubTeamsSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
